### ISSUE TITLE
Hello,Is there a better program than interception in 2019?

### ISSUE THREAD

**Issue by PotatoJet** [MikauSchekzen/TileLemmings#1]
https://github.com/oblitum/Interception/issues/25   I saw your issues there.

**Comment by Furyspark** [comment]
Not sure why you opened this on TileLemmings.

But I haven't come across anything better than Interception on Windows, unfortunately.
On Linux, which is what I'm using most of the time now, there's a combination of libudev and libevdev, which offer more possibilities.

**Comment by PotatoJet** [comment]
> Not sure why you opened this on TileLemmings.
> 
> But I haven't come across anything better than Interception on Windows, unfortunately.
> On Linux, which is what I'm using most of the time now, there's a combination of libudev and libevdev, which offer more possibilities.

Thank you for your kind message.

**Comment by TaranVH** [comment]
QMK + autohotkey is what I use now.
https://www.youtube.com/watch?v=GZEoss4XIgc
